//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyDemo.Manager.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StudyDemo.Manager.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot add a new profile with a null profile dto 的本地化字符串。
        /// </summary>
        internal static string warning_CannotAddProfileWithNullInformation {
            get {
                return ResourceManager.GetString("warning_CannotAddProfileWithNullInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not delete non existing Address 的本地化字符串。
        /// </summary>
        internal static string warning_CannotRemoveNonExistingAddress {
            get {
                return ResourceManager.GetString("warning_CannotRemoveNonExistingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not delete non existing Phone 的本地化字符串。
        /// </summary>
        internal static string warning_CannotRemoveNonExistingPhone {
            get {
                return ResourceManager.GetString("warning_CannotRemoveNonExistingPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not delete non existing Profile 的本地化字符串。
        /// </summary>
        internal static string warning_CannotRemoveNonExistingProfile {
            get {
                return ResourceManager.GetString("warning_CannotRemoveNonExistingProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid arguments when call to ProfileManager&apos;s FindProfiles 的本地化字符串。
        /// </summary>
        internal static string warning_InvalidArgumentForFindProfiles {
            get {
                return ResourceManager.GetString("warning_InvalidArgumentForFindProfiles", resourceCulture);
            }
        }
    }
}
