//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyDemo.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StudyDemo.Domain.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 The Address cannot be null  for ProfileAddress 的本地化字符串。
        /// </summary>
        internal static string exception_ProfileAddressCannotAssociateNullAddress {
            get {
                return ResourceManager.GetString("exception_ProfileAddressCannotAssociateNullAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The AddressType cannot be null  for ProfileAddress 的本地化字符串。
        /// </summary>
        internal static string exception_ProfileAddressCannotAssociateNullAddressType {
            get {
                return ResourceManager.GetString("exception_ProfileAddressCannotAssociateNullAddressType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Profile cannot be null  for ProfileAddress 的本地化字符串。
        /// </summary>
        internal static string exception_ProfileAddressCannotAssociateNullProfile {
            get {
                return ResourceManager.GetString("exception_ProfileAddressCannotAssociateNullProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The City cannot be null  for Address 的本地化字符串。
        /// </summary>
        internal static string exception_ProfileCannotAssociateNullCity {
            get {
                return ResourceManager.GetString("exception_ProfileCannotAssociateNullCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Phone cannot be null  for ProfilePhone 的本地化字符串。
        /// </summary>
        internal static string exception_ProfilePhoneCannotAssociateNullPhone {
            get {
                return ResourceManager.GetString("exception_ProfilePhoneCannotAssociateNullPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The PhoneType cannot be null  for ProfilePhone 的本地化字符串。
        /// </summary>
        internal static string exception_ProfilePhoneCannotAssociateNullPhoneType {
            get {
                return ResourceManager.GetString("exception_ProfilePhoneCannotAssociateNullPhoneType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Profile cannot be null  for ProfilePhone 的本地化字符串。
        /// </summary>
        internal static string exception_ProfilePhoneCannotAssociateNullProfile {
            get {
                return ResourceManager.GetString("exception_ProfilePhoneCannotAssociateNullProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Address Line 1 cannot be null or empty string for Address 的本地化字符串。
        /// </summary>
        internal static string validation_AddressAddressLine1CannotBeNull {
            get {
                return ResourceManager.GetString("validation_AddressAddressLine1CannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Address Line 2 cannot be null or empty string for Address 的本地化字符串。
        /// </summary>
        internal static string validation_AddressAddressLine2CannotBeBull {
            get {
                return ResourceManager.GetString("validation_AddressAddressLine2CannotBeBull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The City  in Address cannot be empty for Address 的本地化字符串。
        /// </summary>
        internal static string validation_AddresscityCannotBeEmpty {
            get {
                return ResourceManager.GetString("validation_AddresscityCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Country in Address cannot be empty for Address 的本地化字符串。
        /// </summary>
        internal static string validation_AddressCountryCannotBeEmpty {
            get {
                return ResourceManager.GetString("validation_AddressCountryCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The State in Address cannot be empty for Address 的本地化字符串。
        /// </summary>
        internal static string validation_AddressStateCannotBeEmpty {
            get {
                return ResourceManager.GetString("validation_AddressStateCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Number cannot be null  for Phone 的本地化字符串。
        /// </summary>
        internal static string validation_PhoneNumberCannotBeNull {
            get {
                return ResourceManager.GetString("validation_PhoneNumberCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Address ID  in ProfileAddress cannot be empty 的本地化字符串。
        /// </summary>
        internal static string validation_ProfileAddressAddressIDCannotBeEmpty {
            get {
                return ResourceManager.GetString("validation_ProfileAddressAddressIDCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Address Type ID  in ProfileAddress cannot be empty 的本地化字符串。
        /// </summary>
        internal static string validation_ProfileAddressAddressTypeIDCannotBeEmpty {
            get {
                return ResourceManager.GetString("validation_ProfileAddressAddressTypeIDCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Profile  ID  in ProfileAddress cannot be empty 的本地化字符串。
        /// </summary>
        internal static string validation_ProfileAddressProfileIDCannotBeEmpty {
            get {
                return ResourceManager.GetString("validation_ProfileAddressProfileIDCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Email cannot be null or empty string for Profile 的本地化字符串。
        /// </summary>
        internal static string validation_ProfileEmailCannotBeBull {
            get {
                return ResourceManager.GetString("validation_ProfileEmailCannotBeBull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The First Name cannot be null or empty string for Profile 的本地化字符串。
        /// </summary>
        internal static string validation_ProfileFirstNameCannotBeNull {
            get {
                return ResourceManager.GetString("validation_ProfileFirstNameCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Last Name cannot be null or empty string for Profile 的本地化字符串。
        /// </summary>
        internal static string validation_ProfileLastNameCannotBeBull {
            get {
                return ResourceManager.GetString("validation_ProfileLastNameCannotBeBull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Phone  ID  in ProfileAddress cannot be empty 的本地化字符串。
        /// </summary>
        internal static string validation_ProfilePhonePhoneIDCannotBeEmpty {
            get {
                return ResourceManager.GetString("validation_ProfilePhonePhoneIDCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The PhoneType  ID  in ProfileAddress cannot be empty 的本地化字符串。
        /// </summary>
        internal static string validation_ProfilePhonePhoneTypeIDCannotBeEmpty {
            get {
                return ResourceManager.GetString("validation_ProfilePhonePhoneTypeIDCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Profile  ID  in ProfileAddress cannot be empty 的本地化字符串。
        /// </summary>
        internal static string validation_ProfilePhoneProfileIDCannotBeEmpty {
            get {
                return ResourceManager.GetString("validation_ProfilePhoneProfileIDCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Zip Code cannot be null or empty string for Address 的本地化字符串。
        /// </summary>
        internal static string validation_ZipCodeCannotBeBull {
            get {
                return ResourceManager.GetString("validation_ZipCodeCannotBeBull", resourceCulture);
            }
        }
    }
}
